GET http://localhost:9090/api/v1/auth/register HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST http://localhost:2121/localhost:9090/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "username": "TESt"
}

###